import React from "react";
import potentials from "./potentials.json";

const Potentials = () => (
  <>
    <h1 className="title">Potentials</h1>
    <section className="textsection">
      <h3 className="subtitle">Introduction</h3>
      <p>{potentials[0]}</p>
    </section>
    <section className="textsection">
      <h3 className="subtitle">Creativity</h3>
      <p>{potentials[1]}</p>
      <p>
        <figure className="inlinefigure">
          <img
            src={process.env.PUBLIC_URL + "/potentials/1.png"}
            style={{
              width: "50%",
              aspectRatio: 1,
              objectFit: "cover",
              padding: "var(--font-size)",
            }}
            alt="AI-Generated Painting A"
          />
          <img
            src={process.env.PUBLIC_URL + "/potentials/2.png"}
            style={{
              width: "50%",
              aspectRatio: 1,
              objectFit: "cover",
              padding: "var(--font-size)",
            }}
            alt="AI-Generated Painting B"
          />
          <img
            src={process.env.PUBLIC_URL + "/potentials/3.png"}
            style={{
              width: "50%",
              aspectRatio: 1,
              objectFit: "cover",
              padding: "var(--font-size)",
            }}
            alt="AI-Generated Painting C"
          />
          <img
            src={process.env.PUBLIC_URL + "/potentials/4.png"}
            style={{
              width: "50%",
              aspectRatio: 1,
              objectFit: "cover",
              padding: "var(--font-size)",
            }}
            alt="AI-Generated Painting D"
          />
          <figcaption>Images Generated by Different AI's</figcaption>
        </figure>
      </p>
      <p>{potentials[2]}</p>
      <p>{potentials[3]}</p>
    </section>
    <section className="textsection">
      <h3 className="subtitle">Economy</h3>
      <p>{potentials[4]}</p>
    </section>
    <section className="textsection">
      <h3 className="subtitle">Bibliography</h3>
      <p>
        Monge, Jim Clyde. “5 AI Art Generators You Should Know About.” Medium, MLearning.ai, 6 Dec.
        2022,
        https://medium.com/mlearning-ai/5-ai-art-generators-you-should-know-about-ed1591cee3b9.{" "}
      </p>

      <p>
        “How You Can Use Iteration Images to Improve Your Art.” Starryai,
        https://www.starryai.com/blog/how-you-can-use-iteration-images-to-improve-your-art.{" "}
      </p>
      <p>
        Shane, Janelle. “Ai-Generated Drawing Prompts.” AI Weirdness, AI Weirdness, 25 May 2021,
        https://www.aiweirdness.com/the-story-behind-ai-drawing-prompts-20-09-02/.
      </p>
    </section>
  </>
);

export default Potentials;
